###
https://ca-customerapi.wonderfuldune-cc8b22b4.northeurope.azurecontainerapps.io/api/customers

###
https://apim-hapiops.azure-api.net/ch3/api/films
Ocp-Apim-Subscription-Key: ccbc24286e7b4536848fdfc7f4760033

###
https://apim-hapiops.azure-api.net/ch2/sessions
Ocp-Apim-Subscription-Key: 091c2c682d5141568c2cec20bfefa4d0

