name: Production deploy

on:
  push:
    branches:
    - 'main'

jobs:
   deploy_to_prod:
    name: 'Production deployment'
    uses: ./.github/workflows/final-main.yml
    secrets: inherit
    with:
      name: 'majnorprod'
      environment: 'prod'